### ISSUE TITLE
Add a GRDP-compliant Cookie Notice

### ISSUE THREAD

**Issue by Kyle-Ski** [kale-stew/climb-log#35]
- [ ] Add a pop-up disclaiming cookie usage
- [ ] Add a Footer with 'explore', 'connect', and 'referral' sub-sections
- [ ] Add a copyright notice
- [ ] Add new logo & feature it in the Footer

**Comment by kale-stew** [comment]
Going to wrap this into my footer rework where I'll be adding legal notices & shortcuts.

**Comment by kale-stew** [comment]
I don't wanna
